# fly.toml app configuration file generated for spudhub on 2024-12-23T17:47:39-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spud-hub'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
